/*
 * Dogs in the Vineyard Non-Player Character API
 * API used to manage Non-Player Characters (NPCs) in a game of Dogs in the Vineyard (DitV)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: motipha@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
